config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Set up root
  root 'listings#index'

  # Override clearance route - #create
  resources :users

  # Start of clearance default routes
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # End of clearance default routes

  # Redirect user from Facebook login
  get '/auth/:provider/callback' => 'sessions#create_from_omniauth'

  # Listing
  resources :listings
  # custom method to show one user's all listings
  get "/users/:id/listings" => "listings#user_listings", as: "user_listings"
  # custom method to verify listing
  post "/listings/:id" => "listings#verify", as: "verify_listing"

  # Redirect from tags
  get 'tags/:tag' => 'listings#index', as: "tag"

  # Reservation
  resources :reservations, except: [:edit, :update]
  # custom method to show current user reservations
  get "/users/:id/reservations" => "reservations#user_reservations", as: "user_reservations"

  # braintree
  get 'braintree/new'
  post 'braintree/checkout'

  # payment
  resources :payments, only: [:create]
end

app/models/listing.rb
class Listing < ApplicationRecord
	include Filterable
	
	belongs_to :user
	has_many :reservations, dependent: :destroy
	has_many :taggings
	has_many :tags, through: :taggings
	validates :title, :address, :price_per_night, presence: true
	mount_uploaders :images, ImageUploader

	scope :city, -> (city) { where city: city }
	scope :price_below, -> (price_per_night) { where("price_per_night <= ?", "#{price_per_night}") }

	def self.search(search)
		if search
			where("title ILIKE :search OR address ILIKE :search OR city ILIKE :search OR postcode ILIKE :search OR state ILIKE :search OR country ILIKE :search", search: "%#{search}%")
		end
	end

	def self.tagged_with(name)
		Tag.find_by_name!(name).listings
	end

	def self.tag_counts
		Tag.select("tags.*, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
	end

	def tag_list
		tags.map(&:name).join(",")
	end

	def tag_list=(names)
		self.tags = names.split(",").map do |n|
			Tag.where(name: n.strip).first_or_create!
		end
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :customer_only, only: [:new, :create]
	before_action :moderator_and_admin_only, only: [:verify]

	def index
		if params[:page].nil? || params[:page].empty?
			@current_page = 1
		else
			@current_page = params[:page].to_i
		end
		offset = (@current_page -  1) * 10
		if params[:tag]
			search_results = Listing.tagged_with(params[:tag]).order(created_at: :desc)
		elsif params[:search]
			search_results = Listing.search(params[:search]).order(created_at: :desc)
		else
			search_results = Listing.filter(params.slice(:price_below, :city)).order(created_at: :desc)
		end
		@pages = search_results.count.div 10 + 1
		@listings = search_results.limit(10).offset(offset)
	end

	def show
		@listing = Listing.find(params[:id])
		@reservation = Reservation.new
	end

	def new
		# allowed?(action: "new_listing", user: current_user)

		@listing = Listing.new
	end

	def create
		@listing = current_user.listings.new(listing_params)
		if @listing.save
			redirect_to @listing
		else
			render 'new'
		end
	end

	def edit
		@listing = Listing.find(params[:id])
		unless current_user.admin?
			unless @listing.user == current_user
				flash[:notice] = "Sorry. Access denied."
				return redirect_back(fallback_location: root_path)
			end
		end
	end

	def update
		@listing = Listing.find(params[:id])
		if current_user.listings.find(params[:id]).update(listing_params)
			redirect_to @listing
		else
			render 'edit'
		end
	end

	def destroy
		@listing = Listing.find(params[:id])
		@listing.destroy
		redirect_to user_listings_path(current_user)
	end

	def user_listings
		@user = User.find(params[:id])
	end

	def verify
		@listing = Listing.find(params[:id])
		@listing.update_attribute(:verified, true)
	end

	private

	def listing_params
		params.require(:listing).permit(:title, :tag_list, :address, :city, :postcode, :state, :country, :price_per_night, :room_type, :smoking_allowed, :pets_allowed, :wifi, :pool, :verified, { images: [] })
	end
end

app/helpers/listings_helper.rb
module ListingsHelper
	def listings_all
		Listing.all
	end
end

app/views/listings/_filter.html.erb
<%= button_tag 'Advanced Filter', id:'filter-button' %>
<br><br>
<div class="row filter" id="filter">
	<%= button_tag 'Price', id:'filter-price-button' %>
	<%= button_tag 'City', id:'filter-city-button' %>
	<%= form_tag listings_path, method: 'get' do %>
		<%= submit_tag 'Apply', class: 'btn btn-default' %>
		<%= button_tag 'Cancel', class: 'btn btn-default' %>
		<div class="well" id="filter-price">
			<%= label_tag :price_per_night %>
			<%= range_field_tag :price_below, listings_all.maximum(:price_per_night), { :min => listings_all.minimum(:price_per_night), :max => listings_all.maximum(:price_per_night), :step => '1.0', id: 'filter-price-bar'} %>
			<div id="filter-price-value">below RM 0</div>
		</div>

		<div class="well" id="filter-city">
			<%= label_tag :City %><br>
			<div class="filter-city-list">
				<% listings_all.distinct.pluck(:city).sort.each do |city| %>
					<span class="filter-city-item">
						<%= check_box_tag :city, city %>
						<%= label_tag city %>
					</span>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/listings/_form.html.erb
<!-- Title -->
<div class="text-field form-group">
  <%= form.label :title, class: 'col-sm-3 control-label' %>
  <div class="col-sm-9">
	  <%= form.text_field :title, required: true, class: 'form-control' %>
  </div>
</div>

<!-- Taggings -->
<div class="text-field form-group">
  <%= form.label :tag_list, "Tags", class: 'col-sm-3 control-label' %>
  <div class="col-sm-9">
	  <%= form.text_field :tag_list, placeholder: 'Tags (separated by commans)', class: 'form-control' %>
  </div>
</div>

<!-- Address -->
<div class="text-field form-group">
  <%= form.label :address, class: 'col-sm-3 control-label' %>
  <div class="col-sm-9">
  	<div class="nested-row nested-col col-sm-12">
		  <%= form.text_field :address, placeholder: 'Address', required: true, class: 'form-control' %>
  	</div>
	  <div class="nested-row">
	  	<div class="nested-col nested-col-left col-sm-9">
			  <%= form.text_field :city, placeholder: 'City', required: true, class: 'form-control' %>
	  	</div>
	  	<div class="nested-col nested-col-right col-sm-3">
			  <%= form.text_field :postcode, placeholder: 'Postcode', required: true, class: 'form-control' %>
	  	</div>
	  </div>
	  <div class="nested-row">
	  	<div class="nested-col nested-col-left col-sm-7">
			  <%= form.text_field :state, placeholder: 'State', required: true, class: 'form-control' %>
	  	</div>
	  	<div class="nested-col nested-col-right col-sm-5">
			  <%= form.text_field :country, placeholder: 'Country', required: true, class: 'form-control' %>
	  	</div>
	  </div>
  </div>
</div>

<!-- Price per night -->
<div class="form-group">
  <%= form.label :price_per_night, class: 'col-sm-3 control-label' %>
  <div class="col-sm-9">
	  <%= form.number_field :price_per_night, value: (number_with_precision(form.object.price_per_night, precision: 2) || 0), required: true, class: 'form-control' %>
  </div>
  <!-- value: "%.2f" -->
</div>

<!-- Room type -->
<div class="form-group">
  <%= form.label :room_type, class: 'col-sm-3 control-label' %>
  <div class="col-sm-9">
  	<%= form.select :room_type, options_for_select(['Entire place', 'Private room', 'Shared room'], 'Private room'), {}, { class: 'form-control' } %>
  </div>
</div>


<!-- Smoking allowed -->
<div class="field form-group">
  <%= form.label :smoking_allowed, class: 'col-sm-3 control-label' %>
  <div class="btn-group col-sm-9" data-toggle="buttons-radio">
		<%= form.label :smoking_allowed, class: 'btn btn-default' do %>
			<%= form.radio_button :smoking_allowed, true %>
			<span>Yes</span>
		<% end %>

		<%= form.label :smoking_allowed, class: 'btn btn-default' do %>
			<%= form.radio_button :smoking_allowed, false %>
			<span>No </span>
		<% end %>
  </div>
</div>

<!-- Pets allowed -->
<div class="field form-group">
  <%= form.label :pets_allowed, class: 'col-sm-3 control-label' %>
  <div class="btn-group col-sm-9" data-toggle="buttons-radio">
		<%= form.label :pets_allowed, class: 'btn btn-default' do %>
			<%= form.radio_button :pets_allowed, true %>
			<span>Yes</span>
		<% end %>

		<%= form.label :pets_allowed, class: 'btn btn-default' do %>
			<%= form.radio_button :pets_allowed, false %>
			<span>No </span>
		<% end %>
  </div>
</div>

<!-- Wifi -->
<div class="field form-group">
  <%= form.label :wifi, class: 'col-sm-3 control-label' %>
  <div class="btn-group col-sm-9" data-toggle="buttons-radio">
		<%= form.label :wifi, class: 'btn btn-default' do %>
			<%= form.radio_button :wifi, true %>
			<span>Yes</span>
		<% end %>

		<%= form.label :wifi, class: 'btn btn-default' do %>
			<%= form.radio_button :wifi, false %>
			<span>No </span>
		<% end %>
  </div>
</div>

<!-- Pool -->
<div class="field form-group">
  <%= form.label :pool, class: 'col-sm-3 control-label' %>
  <div class="btn-group col-sm-9" data-toggle="buttons-radio">
		<%= form.label :pool, class: 'btn btn-default' do %>
			<%= form.radio_button :pool, true %>
			<span>Yes</span>
		<% end %>

		<%= form.label :pool, class: 'btn btn-default' do %>
			<%= form.radio_button :pool, false %>
			<span>No </span>
		<% end %>
  </div>
</div>

<!-- Upload multiple images -->
<div class="file-field form-group">
	<%= form.label :property_image, class: 'col-sm-3 control-label' %>
  <div class="col-sm-9">
	  <%= form.file_field :images, multiple: true %>
	  <%#= form.label :remote_image_url, "or image URL" %><%#= form.text_field :remote_image_url %>
  </div>
</div>

app/views/listings/_image_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
	<!-- Indicators -->
	<ol class="carousel-indicators">
		<% @listing.images.count.times do |x| %>
			<li data-target="#myCarousel" data-slide-to="0" class="<%= 'active' if x == 0 %>"></li>
		<% end %>
	</ol>

	<!-- Images -->
	<div class="carousel-inner">
		<% if @listing.images? %>
			<% @listing.images.each_with_index do |image, index| %>
				<div class="listing-images thumbnail item <%= 'active' if index == 0 %>">
					<%= image_tag image.url.to_s %>
				</div>
			<% end %>
		<% else %>
			<div class="listing-images thumbnail item active %>">
					<%= image_tag 'fallback/image-default.jpg' %>
				</div>
		<% end %>
	</div>

	<!-- Left and right controls -->
	<% if @listing.images? %>
		<% if @listing.images.count > 1 %>
		  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
		    <span class="glyphicon glyphicon-chevron-left"></span>
		    <span class="sr-only">Previous</span>
		  </a>
		  <a class="right carousel-control" href="#myCarousel" data-slide="next">
		    <span class="glyphicon glyphicon-chevron-right"></span>
		    <span class="sr-only">Next</span>
		  </a>
	  <% end %>
  <% end %>
</div>

app/views/listings/edit.html.erb
<h1>This is listings/edit page</h1>

<%= link_to 'Back', listing_path %>

<div id="" class="">
	<!-- Display error messages if any -->
	<% if @listing.errors.any? %>
		<ul>
			<% @listing.errors.full_messages.each do |message| %>
				<li><%= message%></li>
			<% end %>
		</ul>

	<% end %>

  <%= form_for @listing do |form| %>
    <%= render partial: '/listings/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/listings/index.html.erb
<div class="container listing-feed">
	<%= render partial: '/listings/filter' %>
	<div class="row">
		<% @listings.each_slice(2) do |row| %>
			<div class="row">			
				<% row.each do |listing| %>
					<div class="col-sm-12 col-md-6">
						<div class="listing-tag">
							<span>Tags: </span>
							<span><%= raw listing.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></span>
						</div>
						<%= link_to listing_path(listing), target: "_blank" do %>
							<div class="thumbnail">
								<% if listing.images? %>
									<%= image_tag listing.images[0].url.to_s, class: 'img-responsive' %>
								<% else %>
									<%= image_tag 'fallback/image-default.jpg', class: 'img-responsive' %>
								<% end %>
								<div class="caption">
									<span class="listings-item-title">RM<%= number_with_precision(listing.price_per_night, precision: 2) %>  <%= listing.title %></span><br>
									<span><%= listing.address %></span>
								</div>
							</div>
						<% end %>
					</div>
				<% end %>
			</div>
		<% end %>
	</div>

	<ul class="pager">
		<% if @current_page != 1 %>
			<li class="<%= 'active' if @current_page == 1 %>"><%= link_to 'First', controller: "listings", page: 1 %></li>
			<li>...</li>
		<% end %>
		<% if @current_page > 1 %>
			<li class="<%= 'active' if @current_page == @current_page - 1 %>"><%= link_to @current_page - 1, controller: "listings", page: @current_page - 1 %></li>
		<% end %>
		<li class="<%= 'active' if @current_page == @current_page %>"><%= link_to @current_page, controller: "listings", page: @current_page %></li>
		<% if @current_page < @pages + 1 %>
			<li class="<%= 'active' if @current_page == @current_page + 1 %>"><%= link_to @current_page + 1, controller: "listings", page: @current_page + 1 %></li>
		<% end %>
		<% if @current_page != @pages + 1 %>
			<li>...</li>
			<li class="<%= 'active' if @current_page == @pages + 1 %>"><%= link_to 'Last', controller: "listings", page: @pages + 1 %></li>
		<% end %>
	</ul>
</div>

app/views/listings/new.html.erb
<div class="container">
	<h2>Hi, <%= current_user.name %>! Let's get started listing your space.</h2>

	<div id="" class="">
		<!-- Display error messages if any -->
		<% if @listing.errors.any? %>
			<ul>
				<% @listing.errors.full_messages.each do |message| %>
					<li><%= message%></li>
				<% end %>
			</ul>

		<% end %>

	  <%= form_for @listing, html: { class: 'new-listing-form form-horizontal' } do |form| %>
	    <%= render partial: '/listings/form', object: form %>

	    <div class="submit-field form-group">
	    	<div class="col-sm-offset-3 col-sm-9">
		      <%= form.submit 'Create Listing', class: 'btn btn-default' %>
	    	</div>
	    </div>
	  <% end %>
	</div>
</div>

app/views/listings/show.html.erb
<%= render partial: '/listings/image_carousel'%>

<div class="container">
	<div class="col-lg-7 col-md-8">
		<% if signed_in? %>
			<% unless @listing.user.moderator? %>
				<% if @listing.user == current_user || current_user.admin? %>
					<%= link_to 'Edit Listing', edit_listing_path %>
				<% end %>
			<% end %>
			<% unless current_user.customer? || @listing.verified %>
					<%= link_to 'Verify Listing', verify_listing_path, method: :verify, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
			<% end %>
			<br>
		<% end %>

		<!-- Listing title -->
		<div class="row">
			<span class="listing-title">
				<%= @listing.title %>
			</span>
			<span><%= "verified" if @listing.verified %></span>
		</div>

		<!-- Listing taggings -->
		<div class="row">
			<div class="listing-tag">
				<span>Tags: </span>
				<span><%= raw @listing.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></span>
			</div>
		</div>
		
		<!-- Listing address -->
		<div class="row">
			<div class="listing-address">
				<%= @listing.address %>
				<%= @listing.city %> <%= @listing.postcode %>
				<%= @listing.state %> <%= @listing.country %>
			</div>
		</div>
		
		<!-- Listing price per night -->
		<div class="row">
			<span>RM</span>
			<span class="listing-price"><%= number_with_precision(@listing.price_per_night, precision: 2) %></span>
			<span> per night</span>
		</div>

		<!-- Listing host -->
		<div class="row">
			<% host = @listing.user %>
			<div class="listing-host"><%= link_to user_path(host) do %><%= host.name %><% end %></div>
		</div>

		<br>
		<% if signed_in? %>
			<% if @listing.user == current_user || current_user.admin? %>
				<%= link_to 'Delete Listing', listing_path(@listing), method: :delete, data: { confirm: 'Are you sure?' } %>
			<% end %>
		<% end %>
	</div>

	<% if signed_in? %>
		<% if current_user.customer? %>
		<div class="col-lg-3 col-md-3">
			<%= form_for @reservation, html: { class: 'form-horizontal reservation-form' } do |form| %>
				<!-- Checkin / checkout date -->
				<div class="form-group">
					<div class="reservation-col">
						<%= form.label :checkin_date, "Check In", class: 'control-label' %>
						<%= form.text_field :checkin_date, required: true, class: 'form-control datetimepicker_in' %>
					</div>
					<div class="reservation-col">
						<%= form.label :checkout_date, "Check Out", class: 'control-label' %>
						<%= form.text_field :checkout_date, required: true, class: 'form-control datetimepicker_out' %>
					</div>
				</div>

				<%= form.hidden_field :listing_id, value: @listing.id %>

				<!-- Guest No -->
				<div class="form-group">
				  <%= form.label :number_of_guests, class: 'control-label' %>
				  <%= form.number_field :guest_no, required: true, class: 'form-control reservation-guest' %>
				</div>

				<!-- Submit button -->
		    <div class="submit-field form-group">
			      <%= form.submit 'Book', class: 'btn btn-danger' %>
		    </div>
			<% end %>
		</div>
		<% end %>
	<% else %>
		<%= link_to 'Sign In', sign_in_path %>
		<span> / </span>
		<%= link_to 'Sign Up', sign_up_path %>
		<span>to Make a Reservation</span>
	<% end %>
</div>

app/views/listings/user_listings.html.erb
<h4><%= link_to @user.name, user_path %></h4>

<h4><%= @user.listings.count %> listings</h4>

<% @user.listings.each do |listing| %>
	<%= link_to listing_path(listing), target: "_blank" do %>
		<div>
			RM<%= number_with_precision(listing.price_per_night, precision: 2) %>
			<%= listing.title %>
		</div>
	<% end %>
<% end %>