config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Set up root
  root 'listings#index'

  # Override clearance route - #create
  resources :users

  # Start of clearance default routes
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # End of clearance default routes

  # Redirect user from Facebook login
  get '/auth/:provider/callback' => 'sessions#create_from_omniauth'

  # Listing
  resources :listings
  # custom method to show one user's all listings
  get "/users/:id/listings" => "listings#user_listings", as: "user_listings"
  # custom method to verify listing
  post "/listings/:id" => "listings#verify", as: "verify_listing"

  # Redirect from tags
  get 'tags/:tag' => 'listings#index', as: "tag"

  # Reservation
  resources :reservations, except: [:edit, :update]
  # custom method to show current user reservations
  get "/users/:id/reservations" => "reservations#user_reservations", as: "user_reservations"

  # braintree
  get 'braintree/new'
  post 'braintree/checkout'

  # payment
  resources :payments, only: [:create]
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :authentications, dependent: :destroy
  has_many :listings, dependent: :destroy
  has_many :reservations, dependent: :destroy
  enum role: [:customer, :moderator, :admin]
  mount_uploader :avatar, AvatarUploader

  def self.create_with_auth_and_hash(authentication, auth_hash)
    user = self.create!(
      name: auth_hash["extra"]["raw_info"]["name"],
      email: auth_hash["extra"]["raw_info"]["email"],
      password: SecureRandom.hex(10)
    )

    user.authentications << authentication
    return user
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_action :admin_only, only: [:index, :destroy]

  def index
    @users = User.all.order(:id)
  end

  def show
    # allowed?(action: "show_user", user: current_user)

    if params[:id].nil?
      @user = current_user
    else
      @user = User.find(params[:id])
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render "users/new"
    end
  end

  def edit
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        flash[:notice] = "Sorry. Access denied."
        return redirect_back(fallback_location: root_path)
      end
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :avatar, :remote_avatar_url)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-field input-group form-group">
  <%#= form.label :name %>
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <%= form.text_field :name, placeholder: 'Name', required: true, class: 'form-control' %>
</div>

<div class="text-field input-group form-group">
  <%#= form.label :email %>
  <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
  <%= form.text_field :email, type: 'email', placeholder: 'Email', required: true, class: 'form-control' %>
</div>

<div class="password-field input-group form-group">
  <%#= form.label :password %>
  <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
  <%= form.password_field :password, placeholder: 'Password', required: true, class: 'form-control' %>
</div>

app/views/users/edit.html.erb
<div class="edit-profile panel panel-default">
	<div class="panel-heading">
		Edit Profile
	</div>
	<div class="panel-body">
	  <%= form_for @user, html: { class: 'form-horizontal' } do |form| %>
			<div class="file-field form-group">
		  	<%= form.label :profile_photo, class: 'col-sm-3 control-label' %>
			  <div class="col-sm-9">
				  <%= form.file_field :avatar, class: '' %><%= form.label :remote_avatar_url, "or image URL" %><%= form.text_field :remote_avatar_url %>
			  </div>
			</div>

			<div class="text-field form-group">
			  <%= form.label :name, class: 'col-sm-3 control-label' %>
			  <div class="col-sm-9">
				  <%= form.text_field :name, placeholder: 'Name', class: 'form-control' %>
			  </div>
			</div>

			<div class="text-field form-group">
			  <%= form.label :email, class: 'col-sm-3 control-label' %>
			  <div class="col-sm-9">
				  <%= form.text_field :email, type: 'email', placeholder: 'Email', class: 'form-control' %>
			  </div>
			</div>
			
	    <div class="submit-field form-group">
	    	<div class="col-sm-offset-2 col-sm-9">
		      <%= form.submit 'Save', class: 'btn btn-danger' %>
	    	</div>
	    </div>
	  <% end %>
	</div>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
	<p><%= user.id %>. <%= user.name %> | <%= link_to 'Edit User', edit_user_path(user) %> | <%= link_to 'Delete User', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% end %>

app/views/users/new.html.erb
<body class="bg1">
  <div id="clearance" class="sign-up well text-center vertical-align">
    <h2><%= t(".title") %></h2>

    <%= form_for @user do |form| %>
      <%= render partial: '/users/form', object: form %>

      <div class="submit-field form-group">
        <%= form.submit %>
      </div>

      <div class="other-links form-group">
        <%= link_to "Sign up with Facebook", "/auth/facebook" %>
        <!-- /auth/facebook?display=popup -->
        <!-- /auth/facebook?scope=email -->
      </div>
    <% end %>
  </div>
</body>

app/views/users/show.html.erb
<div class="container-fluid profile-page">
	<div class="row text-center">
		<!-- Avatar image -->
		<div class="col-lg-3 col-md-4 hide-sm">
			<div class="text-center profile-avatar">
				<%= image_tag @user.avatar.url.to_s, class: 'img-responsive' %>
			</div>
		</div>

		<div class="col-lg-9 col-md-8 col-sm-12 text-left">
			<h1 class="text-left">Hey, I'm <%= @user.name %>!</h1>
			<% if @user == current_user %>
				<div><%= link_to 'Edit Profile', edit_user_path %></div>
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-3 col-md-4 hide-sm">
			<!-- Display user/:id/listings -->
			<div>
				<% user_listings = @user.listings %>
				<h2 class="text-left">Listings <small>(<%= user_listings.count %>)</small></h2>
				<ul class="list-group">
					<% user_listings.first(3).each do |listing| %>
						<li class="list-group-item"><%= link_to listing_path(listing), target: "_blank" do %><%= listing.title %><% end %></li>
					<% end %>
				</ul>
			</div>
			<%= link_to 'View all listings', user_listings_path %>
		</div>

		<div class="col-lg-9 col-md-8 col-sm-12">
			<!-- Display user/:id/reviews -->
			<h2 class="text-left">Reviews <small>(<%= 0 %>)</small></h2>
		</div>
	</div>
</div>