config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Set up root
  root 'listings#index'

  # Override clearance route - #create
  resources :users

  # Start of clearance default routes
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # End of clearance default routes

  # Redirect user from Facebook login
  get '/auth/:provider/callback' => 'sessions#create_from_omniauth'

  # Listing
  resources :listings
  # custom method to show one user's all listings
  get "/users/:id/listings" => "listings#user_listings", as: "user_listings"
  # custom method to verify listing
  post "/listings/:id" => "listings#verify", as: "verify_listing"

  # Redirect from tags
  get 'tags/:tag' => 'listings#index', as: "tag"

  # Reservation
  resources :reservations, except: [:edit, :update]
  # custom method to show current user reservations
  get "/users/:id/reservations" => "reservations#user_reservations", as: "user_reservations"

  # braintree
  get 'braintree/new'
  post 'braintree/checkout'

  # payment
  resources :payments, only: [:create]
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :user
	belongs_to :listing
  has_many :payments, dependent: :destroy

  validates :guest_no, numericality: { greater_than: 0}, presence: true
  validate :checkin_date_cannot_be_in_the_past,
    :checkout_date_cannot_be_less_than_checkin_date,
    :date_cannot_be_overlap
  before_save :calculate_total_amount

  def checkin_date_cannot_be_in_the_past
    errors.add(:checkin_date, "can't be in the past") if
      !checkin_date.blank? and checkin_date < Date.today
  end

  def checkout_date_cannot_be_less_than_checkin_date
    errors.add(:checkout_date, "must be more than  Checkin date") if
      !checkout_date.blank? and checkout_date <= checkin_date
  end

  def date_cannot_be_overlap
    Reservation.where(listing_id: listing_id).each do |reservation|
      if (checkin_date..checkout_date).overlaps?(reservation.checkin_date..reservation.checkout_date)
        return errors.add(:checkin_date, "can't be overlap with other reservations")
      end
    end
  end

  def calculate_total_amount
    self.total_amount = self.listing.price_per_night * (self.checkout_date.to_date() - self.checkin_date.to_date()).to_i
  end

  def send_reservation_email_to_host
    ReservationJob.perform_later(self.user, self.listing.user, self.id)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_action :customer_only, only: [:new, :create]
	before_action :admin_only, only: [:index]

	def index
	end

	def show
		@reservation = Reservation.find(params[:id])
	end

	def new
		@reservation = Reservation.new
	end
	
	def create
		@reservation = current_user.reservations.new(reservation_params)
		if @reservation.save
			# Change the below to background job
			# ReservationMailer.booking_email(@reservation.user, @reservation.listing.user, @reservation.id).deliver_now
			# Move below model logic into model
			# ReservationJob.perform_later(@reservation.user, @reservation.listing.user, @reservation.id)
			@reservation.send_reservation_email_to_host
			redirect_to @reservation
		else
			render 'new'
		end
	end

	def destroy
		@reservation = Reservation.find(params[:id])
		@reservation.destroy
		redirect_to user_reservations_path(@reservation.user_id)
	end

	def user_reservations
    if params[:id].nil?
      @user = current_user
    else
      @user = User.find(params[:id])
    end
	end

	private

	def reservation_params
		params.require(:reservation).permit(:listing_id, :checkin_date, :checkout_date, :guest_no)
	end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/new.html.erb
<div class="container">
	<div>Reservations</div>

	<div id="" class="error">
		<!-- Display error messages if any -->
		<% if @reservation.errors.any? %>
			<ul>
				<% @reservation.errors.full_messages.each do |message| %>
					<li><%= message%></li>
				<% end %>
			</ul>

		<% end %>
	</div>

	<%= form_for @reservation, html: { class: 'form-horizontal reservation-form' } do |form| %>
		<!-- Checkin / checkout date -->
		<div class="form-group">
			<div class="reservation-col">
				<%= form.label :checkin_date, "Check In", class: 'control-label' %>
				<%= form.text_field :checkin_date, class: 'form-control datetimepicker_in' %>
			</div>
			<div class="reservation-col">
				<%= form.label :checkout_date, "Check Out", class: 'control-label' %>
				<%= form.text_field :checkout_date, class: 'form-control datetimepicker_out' %>
			</div>
		</div>

		<%= form.hidden_field :listing_id %>

		<!-- Guest No -->
		<div class="form-group">
		  <%= form.label :number_of_guests, class: 'control-label' %>
		  <%= form.number_field :guest_no, required: true, class: 'form-control reservation-guest' %>
		</div>

		<!-- Submit button -->
    <div class="submit-field form-group">
	      <%= form.submit 'Book', class: 'btn btn-danger' %>
    </div>
	<% end %>

</div>

app/views/reservations/show.html.erb
<div class="container">
	<div>Your Reservation</div>

	<div id="" class="error">
		<!-- Display error messages if any -->
		<% if @reservation.errors.any? %>
			<ul>
				<% @reservation.errors.full_messages.each do |message| %>
					<li><%= message%></li>
				<% end %>
			</ul>

		<% end %>
	</div>

	<div class="row">
		<% listing = @reservation.listing %>

		<!-- Listing image -->
		<div class="col-lg-2">
			<% if listing.images? %>
				<%= image_tag listing.images[0].url.to_s, class: 'img-responsive' %>
			<% else %>
				<img class="img-responsive" src="http://via.placeholder.com/200x200" alt="">
			<% end %>
		</div>

		<!-- Listing title -->
		<div>
			<%= link_to listing_path(listing), class: 'listing-title' do %>
				<%= listing.title %>
			<% end %>
		</div>

		<!-- Reservation date -->
		<div>
			Check In date: <%= @reservation.checkin_date %><br>
			Check Out date: <%= @reservation.checkout_date %>
		</div>

		<!-- Reservation total amount -->
		<div>
			Total amount: RM<%= number_with_precision(@reservation.total_amount, precision: 2) %>
		</div>

		<div>
			<% if @reservation.user == current_user %>
				<% if paid? %>
					Paid
				<% else %>
					<%= link_to "Make Payment", braintree_new_path(:reservation_id => @reservation.id), class: 'btn btn-danger' %>
				<% end %>
			<% end %>
		</div>

		<div>
			<% if @reservation.user == current_user || current_user.admin? %>
				<%= link_to 'Cancel booking', reservation_path(@reservation), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
			<% end %>
		</div>

	</div>

</div>

app/views/reservations/user_reservations.html.erb
<h4><%= link_to @user.name, user_path %></h4>

<h4><%= @user.reservations.count %> reservations</h4>

<% @user.reservations.each do |reservation| %>
	<% listing = reservation.listing %>
	<div class="row reservation-item">
		<!-- Listing image -->
		<div class="col-lg-2 col-md-2">
			<% if listing.images? %>
				<%= image_tag listing.images[0].url.to_s, class: 'img-responsive' %>
			<% else %>
				<img class="img-responsive" src="http://via.placeholder.com/200x200" alt="">
			<% end %>
		</div>

		<div class="col-lg-10">		
			<%= link_to 'View more details', reservation_path(reservation) %><br>
			<%= link_to listing_path(listing), class: 'listing-title' do %>
				<%= listing.title %>
			<% end %><br>
			Total amount: RM<%= number_with_precision(reservation.total_amount, precision: 2) %><br>
		</div>
	</div>
<% end %>