config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Set up root
  root 'listings#index'

  # Override clearance route - #create
  resources :users

  # Start of clearance default routes
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # End of clearance default routes

  # Redirect user from Facebook login
  get '/auth/:provider/callback' => 'sessions#create_from_omniauth'

  # Listing
  resources :listings
  # custom method to show one user's all listings
  get "/users/:id/listings" => "listings#user_listings", as: "user_listings"
  # custom method to verify listing
  post "/listings/:id" => "listings#verify", as: "verify_listing"

  # Redirect from tags
  get 'tags/:tag' => 'listings#index', as: "tag"

  # Reservation
  resources :reservations, except: [:edit, :update]
  # custom method to show current user reservations
  get "/users/:id/reservations" => "reservations#user_reservations", as: "user_reservations"

  # braintree
  get 'braintree/new'
  post 'braintree/checkout'

  # payment
  resources :payments, only: [:create]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    coded by <a href="https://github.com/leesc22" target="_blank">Lee Siew Ching</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "PairBnB", root_path, class: "logo" %>
		<nav>
			<!-- Searchbar -->
			<%= form_tag listings_path, method: 'get', class: 'navbar-form navbar-left' do %>
				<div class="input-group">
					<%= text_field_tag :search, params[:search], placeholder: 'Search for ...', class: 'form-control' %>
					<span class="input-group-btn"><%= submit_tag "Go!", name: nil, class: 'btn btn-default' %></span>
				</div>
			<% end %>

			<ul class="nav navbar-nav navbar-right">
				<% if signed_in? %>
					<li><%= link_to 'Become a Host', new_listing_path if current_user.customer? %></li>
					<li><%= link_to 'Trips', user_reservations_path(current_user)  if current_user.customer? %></li>
					<li class="navbar-profile">
						<%= link_to current_user do %>
							<%= image_tag current_user.avatar.url(:thumb).to_s %>
						<% end %>
					</li>
					<li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
				<% else %>
					<% if Clearance.configuration.allow_sign_up? %>
					<li><%= link_to t(".sign_up"), sign_up_path %></li>
					<% end %>
				  <li><%= link_to t(".sign_in"), sign_in_path %></li>
				<% end %>					
			</ul>
		</nav>	

		<div id="flash">
		  <% flash.each do |key, value| %>
		    <div class="flash <%= key %>"><%= value %></div>
		  <% end %>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PairBnb</title>
    <%= csrf_meta_tags %>

    <!-- Load the Client component. -->
    <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

    <!-- Load the Hosted Fields component. -->
    <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: '/layouts/header' %>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
      <%= render partial: '/layouts/footer' %>
    </div>
  </body>
</html>